services:
  - type: web
    name: infectious-diseases-mapping
    env: docker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "infectious-diseases-mapping.onrender.com"
      - key: DEBUG
        value: "False"
