# Generated by Django 6.0.2 on 2026-02-19 00:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativeBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="P-Code or District ID", max_length=20, unique=True
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("province", "Province"),
                            ("district", "District"),
                            ("ward", "Ward"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Administrative Boundaries",
            },
        ),
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("district_name", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "verbose_name_plural": "Health Facilities",
            },
        ),
        migrations.CreateModel(
            name="DiseaseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("cholera", "Cholera"),
                            ("typhoid", "Typhoid Fever"),
                            ("dysentery", "Dysentery"),
                            ("malaria", "Malaria"),
                            ("yellow_fever", "Yellow Fever"),
                            ("schistosomiasis", "Schistosomiasis"),
                            ("measles", "Measles"),
                            ("afp", "Acute Flaccid Paralysis"),
                            ("anthrax", "Anthrax"),
                            ("rabies", "Rabies"),
                            ("tb", "Tuberculosis"),
                            ("covid19", "COVID-19"),
                            ("noma", "Noma"),
                            ("unknown", "Unknown Origin"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waterborne", "Waterborne & Enteric"),
                            ("vector", "Vector-Borne"),
                            ("vaccine", "Vaccine-Preventable"),
                            ("vhf", "Viral Haemorrhagic Fevers"),
                            ("zoonotic", "Zoonotic"),
                            ("respiratory", "Respiratory & Airborne"),
                            ("other", "Other Notifiable"),
                        ],
                        default="other",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "date_of_onset",
                    models.DateField(
                        blank=True, help_text="Date symptoms started", null=True
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Suspected"), (2, "Probable"), (3, "Confirmed")],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("active", "Active / Treatment"),
                            ("recovered", "Recovered"),
                            ("deceased", "Deceased"),
                            ("referred", "Referred Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="surveillance.healthfacility",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["disease_type"], name="surveillanc_disease_094dde_idx"
                    ),
                    models.Index(
                        fields=["date_of_onset"], name="surveillanc_date_of_deb34b_idx"
                    ),
                ],
            },
        ),
    ]
