# Generated by Django 6.0.2 on 2026-02-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasecase",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="e.g., Patient Home, Makonde District",
                max_length=255,
                null=True,
            ),
        ),
    ]
