# Generated by Django 6.0.2 on 2026-02-25 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0002_diseasecase_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasecase",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="healthfacility",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
    ]
