# Generated by Django 6.0.2 on 2026-02-26 23:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0003_alter_diseasecase_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasecase",
            name="age",
            field=models.IntegerField(blank=True, help_text="Age in years", null=True),
        ),
        migrations.AddField(
            model_name="diseasecase",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="diseasecase",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="surveillanc_locatio_8f106c_gist"
            ),
        ),
    ]
