# Generated by Django 6.0.2 on 2026-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0004_diseasecase_age_diseasecase_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasecase",
            name="disease_type",
            field=models.CharField(
                choices=[
                    ("cholera", "Cholera"),
                    ("tb", "Tuberculosis"),
                    ("hiv", "HIV/AIDS"),
                ],
                max_length=50,
            ),
        ),
    ]
