# Generated by Django 6.0.2 on 2026-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0005_alter_diseasecase_disease_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasecase",
            name="variant",
            field=models.CharField(
                blank=True,
                help_text="Specific strain or variant, e.g., Cholera O1 Ogawa, MDR-TB",
                max_length=100,
                null=True,
            ),
        ),
    ]
