# Generated by Django 6.0.2 on 2026-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0007_diseasecase_reported_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasecase",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diseasecase",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
