# Generated by Django 6.0.2 on 2026-03-23 19:27

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0008_diseasecase_latitude_diseasecase_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CholeraCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Patient Home, Makonde District",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age in years", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("cholera", "Cholera"),
                            ("tb", "Tuberculosis"),
                            ("hiv", "HIV/AIDS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="Specific strain or variant, e.g., Cholera O1 Ogawa, MDR-TB",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waterborne", "Waterborne & Enteric"),
                            ("vector", "Vector-Borne"),
                            ("vaccine", "Vaccine-Preventable"),
                            ("vhf", "Viral Haemorrhagic Fevers"),
                            ("zoonotic", "Zoonotic"),
                            ("respiratory", "Respiratory & Airborne"),
                            ("other", "Other Notifiable"),
                        ],
                        default="other",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "date_of_onset",
                    models.DateField(
                        blank=True, help_text="Date symptoms started", null=True
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Suspected"), (2, "Probable"), (3, "Confirmed")],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("active", "Active / Treatment"),
                            ("recovered", "Recovered"),
                            ("deceased", "Deceased"),
                            ("referred", "Referred Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cholera Cases",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HIVCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Patient Home, Makonde District",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age in years", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("cholera", "Cholera"),
                            ("tb", "Tuberculosis"),
                            ("hiv", "HIV/AIDS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="Specific strain or variant, e.g., Cholera O1 Ogawa, MDR-TB",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waterborne", "Waterborne & Enteric"),
                            ("vector", "Vector-Borne"),
                            ("vaccine", "Vaccine-Preventable"),
                            ("vhf", "Viral Haemorrhagic Fevers"),
                            ("zoonotic", "Zoonotic"),
                            ("respiratory", "Respiratory & Airborne"),
                            ("other", "Other Notifiable"),
                        ],
                        default="other",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "date_of_onset",
                    models.DateField(
                        blank=True, help_text="Date symptoms started", null=True
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Suspected"), (2, "Probable"), (3, "Confirmed")],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("active", "Active / Treatment"),
                            ("recovered", "Recovered"),
                            ("deceased", "Deceased"),
                            ("referred", "Referred Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "HIV Cases",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TBCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Patient Home, Makonde District",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age in years", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("cholera", "Cholera"),
                            ("tb", "Tuberculosis"),
                            ("hiv", "HIV/AIDS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="Specific strain or variant, e.g., Cholera O1 Ogawa, MDR-TB",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waterborne", "Waterborne & Enteric"),
                            ("vector", "Vector-Borne"),
                            ("vaccine", "Vaccine-Preventable"),
                            ("vhf", "Viral Haemorrhagic Fevers"),
                            ("zoonotic", "Zoonotic"),
                            ("respiratory", "Respiratory & Airborne"),
                            ("other", "Other Notifiable"),
                        ],
                        default="other",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "date_of_onset",
                    models.DateField(
                        blank=True, help_text="Date symptoms started", null=True
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Suspected"), (2, "Probable"), (3, "Confirmed")],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("active", "Active / Treatment"),
                            ("recovered", "Recovered"),
                            ("deceased", "Deceased"),
                            ("referred", "Referred Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TB Cases",
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="diseasecase",
            name="surveillanc_disease_094dde_idx",
        ),
        migrations.RemoveIndex(
            model_name="diseasecase",
            name="surveillanc_date_of_deb34b_idx",
        ),
        migrations.RemoveIndex(
            model_name="diseasecase",
            name="surveillanc_locatio_8f106c_gist",
        ),
        migrations.AddField(
            model_name="choleracase",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_cases",
                to="surveillance.healthfacility",
            ),
        ),
        migrations.AddField(
            model_name="choleracase",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_reported_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hivcase",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_cases",
                to="surveillance.healthfacility",
            ),
        ),
        migrations.AddField(
            model_name="hivcase",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_reported_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tbcase",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_cases",
                to="surveillance.healthfacility",
            ),
        ),
        migrations.AddField(
            model_name="tbcase",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_reported_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="diseasecase",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="diseasecase",
            name="reported_by",
        ),
        migrations.AddIndex(
            model_name="choleracase",
            index=models.Index(
                fields=["disease_type"], name="surveillanc_disease_e8c354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="choleracase",
            index=models.Index(
                fields=["date_of_onset"], name="surveillanc_date_of_1ed681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="choleracase",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="surveillanc_locatio_8b928b_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="hivcase",
            index=models.Index(
                fields=["disease_type"], name="surveillanc_disease_767675_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hivcase",
            index=models.Index(
                fields=["date_of_onset"], name="surveillanc_date_of_f016d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hivcase",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="surveillanc_locatio_aefa67_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="tbcase",
            index=models.Index(
                fields=["disease_type"], name="surveillanc_disease_ab8a36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tbcase",
            index=models.Index(
                fields=["date_of_onset"], name="surveillanc_date_of_65ec25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tbcase",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="surveillanc_locatio_e909ed_gist"
            ),
        ),
        migrations.DeleteModel(
            name="DiseaseCase",
        ),
    ]
