# Generated by Django 6.0.2 on 2026-03-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0009_choleracase_hivcase_tbcase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choleracase",
            name="disease_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hivcase",
            name="disease_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tbcase",
            name="disease_type",
            field=models.CharField(max_length=100),
        ),
    ]
