# Generated by Django 6.0.2 on 2026-05-14 20:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0011_genericdiseasecase_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MalariaCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Patient Home, Makonde District",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age in years", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("disease_type", models.CharField(max_length=100)),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="Specific strain or variant, e.g., Cholera O1 Ogawa, MDR-TB",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waterborne", "Waterborne & Enteric"),
                            ("vector", "Vector-Borne"),
                            ("vaccine", "Vaccine-Preventable"),
                            ("vhf", "Viral Haemorrhagic Fevers"),
                            ("zoonotic", "Zoonotic"),
                            ("respiratory", "Respiratory & Airborne"),
                            ("other", "Other Notifiable"),
                        ],
                        default="other",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "date_of_onset",
                    models.DateField(
                        blank=True, help_text="Date symptoms started", null=True
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Suspected"), (2, "Probable"), (3, "Confirmed")],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("active", "Active / Treatment"),
                            ("recovered", "Recovered"),
                            ("deceased", "Deceased"),
                            ("referred", "Referred Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_cases",
                        to="surveillance.healthfacility",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reported_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Malaria Cases",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["disease_type"], name="surveillanc_disease_0a8db5_idx"
                    ),
                    models.Index(
                        fields=["date_of_onset"], name="surveillanc_date_of_1d8e48_idx"
                    ),
                    models.Index(
                        fields=["date_reported"], name="surveillanc_date_re_b5e422_idx"
                    ),
                    models.Index(
                        fields=["facility"], name="surveillanc_facilit_724df8_idx"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="surveillanc_locatio_88f4ab_gist"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TyphoidCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Patient Home, Makonde District",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age in years", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("disease_type", models.CharField(max_length=100)),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="Specific strain or variant, e.g., Cholera O1 Ogawa, MDR-TB",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waterborne", "Waterborne & Enteric"),
                            ("vector", "Vector-Borne"),
                            ("vaccine", "Vaccine-Preventable"),
                            ("vhf", "Viral Haemorrhagic Fevers"),
                            ("zoonotic", "Zoonotic"),
                            ("respiratory", "Respiratory & Airborne"),
                            ("other", "Other Notifiable"),
                        ],
                        default="other",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                (
                    "date_of_onset",
                    models.DateField(
                        blank=True, help_text="Date symptoms started", null=True
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Suspected"), (2, "Probable"), (3, "Confirmed")],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("active", "Active / Treatment"),
                            ("recovered", "Recovered"),
                            ("deceased", "Deceased"),
                            ("referred", "Referred Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_cases",
                        to="surveillance.healthfacility",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reported_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Typhoid Cases",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["disease_type"], name="surveillanc_disease_6d919b_idx"
                    ),
                    models.Index(
                        fields=["date_of_onset"], name="surveillanc_date_of_5dd3eb_idx"
                    ),
                    models.Index(
                        fields=["date_reported"], name="surveillanc_date_re_e77bf6_idx"
                    ),
                    models.Index(
                        fields=["facility"], name="surveillanc_facilit_4fc68b_idx"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="surveillanc_locatio_ec62ad_gist"
                    ),
                ],
            },
        ),
    ]
