# Generated by Django 6.0.2 on 2026-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0012_malariacase_typhoidcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrativeboundary",
            name="level",
            field=models.CharField(
                choices=[("province", "Province"), ("district", "District")],
                max_length=20,
            ),
        ),
    ]
